---
kind: pipeline
name: python-3-7
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.7
  environment:
    TOX_WORK_DIR: /tmp/.tox
    HAS_COVERALLS: true
    COVERALLS_SERVICE_NAME: PySHACL-Drone
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e py37
- name: type-checking
  image: python:3.7
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint
- name: lint
  image: python:3.7
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint

volumes:
- name: tox_cache
  temp: {}

---
kind: pipeline
name: python-3-8
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.8
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e py38
- name: type-checking
  image: python:3.8
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint
- name: lint
  image: python:3.8
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint

volumes:
- name: tox_cache
  temp: {}

---
kind: pipeline
name: python-3-9
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.9
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e py39
- name: type-checking
  image: python:3.9
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint
- name: lint
  image: python:3.9
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint

volumes:
- name: tox_cache
  temp: {}
